# Site settings
title: LTI™ Documentation
baseurl: "/lti_docs" # the subpath of your site, e.g. /blog/
url: "http://instructure.github.io" # the base hostname & protocol for your site
twitter_username: instructure
github_username:  instructure

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"